name:                chiefc
version:             0.1.0.0

dependencies:
- base

ghc-options:
- -Weverything
- -Werror
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-implicit-prelude
- -Wno-missing-kind-signatures
- -Wno-prepositive-qualified-module

executables:
  chiefc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
